// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// ConvertFileParams defines parameters for ConvertFile.
type ConvertFileParams struct {
	// Filename Required: Original filename to parse (e.g. build.mcstructure, design.schem, world.litematic)
	Filename *string `form:"filename,omitempty" json:"filename,omitempty"`

	// Output Filename for the downloaded response (e.g. custom.nbt)
	Output *string `form:"output,omitempty" json:"output,omitempty"`

	// MinX Minimum X coordinate (only for mcworld)
	MinX *int `form:"min_x,omitempty" json:"min_x,omitempty"`

	// MaxX Maximum X coordinate (only for mcworld)
	MaxX *int `form:"max_x,omitempty" json:"max_x,omitempty"`

	// MinY Minimum Y coordinate (only for mcworld)
	MinY *int `form:"min_y,omitempty" json:"min_y,omitempty"`

	// MaxY Maximum Y coordinate (only for mcworld)
	MaxY *int `form:"max_y,omitempty" json:"max_y,omitempty"`

	// MinZ Minimum Z coordinate (only for mcworld)
	MinZ *int `form:"min_z,omitempty" json:"min_z,omitempty"`

	// MaxZ Maximum Z coordinate (only for mcworld)
	MaxZ *int `form:"max_z,omitempty" json:"max_z,omitempty"`

	// Dimension Dimension ID (0=Overworld, 1=Nether, 2=The End)
	Dimension *int `form:"dimension,omitempty" json:"dimension,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ConvertFile request
	ConvertFile(ctx context.Context, params *ConvertFileParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ConvertFile(ctx context.Context, params *ConvertFileParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConvertFileRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewConvertFileRequest generates requests for ConvertFile
func NewConvertFileRequest(server string, params *ConvertFileParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Filename != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filename", *params.Filename, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Output != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "output", *params.Output, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MinX != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "min_x", *params.MinX, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MaxX != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "max_x", *params.MaxX, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MinY != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "min_y", *params.MinY, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MaxY != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "max_y", *params.MaxY, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MinZ != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "min_z", *params.MinZ, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MaxZ != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "max_z", *params.MaxZ, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Dimension != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dimension", *params.Dimension, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ConvertFileWithResponse request
	ConvertFileWithResponse(ctx context.Context, params *ConvertFileParams, reqEditors ...RequestEditorFn) (*ConvertFileResponse, error)
}

type ConvertFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ConvertFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConvertFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ConvertFileWithResponse request returning *ConvertFileResponse
func (c *ClientWithResponses) ConvertFileWithResponse(ctx context.Context, params *ConvertFileParams, reqEditors ...RequestEditorFn) (*ConvertFileResponse, error) {
	rsp, err := c.ConvertFile(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConvertFileResponse(rsp)
}

// ParseConvertFileResponse parses an HTTP response from a ConvertFileWithResponse call
func ParseConvertFileResponse(rsp *http.Response) (*ConvertFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConvertFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6SVX0/jOhDFv4o14oGL0jQF3RdLPMDlVuJK/BFFugsrhNx42o42tsPYbhuqfveV0z+w",
	"u0Urun1omzie8zsTzfECyI4cyAUEChWChHPU7Mpv4vr8Xvzj7BQ5IIuz20vIYIrsyVmQ0MsLWGbgarSq",
	"JpBwkhd5DzKoVZj4VK+bvmrnQ/p1NbIK5OylBgnrsn2qsN3BymBA9iC/LkCjL5nqsNK5w5dIjFqKG6Yx",
	"WVWJEVVolUERnKgVexSHmI9zMYxU6dyUPnAsQ2TMhEZPY5v7coImEzPHlc4rCmhUoPIvyICSxktEbiCD",
	"VBQkbOpDBu1G1XanqdOaD0x2DMtl9jNof0M1cizCBIV2M1s5pVELRl87uwUtow/O5HYYPkJwMdQx/ACg",
	"caRiFUBCuX4pOlWA7PdoV2TJRCO+iNI51mRVQHHobNW0sKZsG/MRiyH7PN/VC7IBx8g7FdX8TxTV/POK",
	"a48Pe3ts9vT4sLfHZk+Pj3t7fN3T4+PeHj+reEEGbcoYcXkhDovTmylyK5KJ3uk1hglyJo5P7yco/rUf",
	"KutNld0jVGS/kjxlsBnTNr6Oi2K15z3dIJYlej+KVdWI7Ry2iSQYQ2SLWigvhmQVN8kf+GhM+r9NPbEJ",
	"2PdRJRyn69ZpyrX/1FSJ9XzPO8qoV2c7qqaxCjhTTaflXiVqopyEUF9hmLiUrrc3g/u3WFAz/1yzm6fu",
	"RKb0dN9KOYjDtMhWqpmXb5XlweLs/4GUdzgmZ5eyUmaolUyp3j0uen93ipPOSa87irZM4r57sNgeEv31",
	"zfyM7bJLdurKltDDMn12O1m1qmNQk+ok5nQKwFH3CJ6W3wMAAP//dzakIJ0GAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
